using Alerting.ML.Engine.Alert;
using Alerting.ML.Engine.Storage;

namespace Alerting.ML.Engine.Optimizer.Events;

/// <summary>
/// Indicates that random configuration was added to current generation.
/// </summary>
/// <param name="RandomConfiguration">Configuration that was randomly generated by <see cref="IConfigurationFactory{TConfiguration}"/></param>
/// <param name="AggregateVersion">Version of the aggregate current event is applied.</param>
/// <typeparam name="T"></typeparam>
public record RandomConfigurationAddedEvent<T>(T RandomConfiguration, int AggregateVersion) : IEvent
    where T : AlertConfiguration;